server:
  port: 8888

db:
  type: postgres
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  name: go-api-template
  sslmode: disable

# database:
#   driver: mysql
#   host: localhost
#   port: 3306
#   user: root
#   password: password
#   name: goapi

jwt:
  secret: your_jwt_secret
  expires_in: 3600
